---
repos:
  # ######################################################################
  #
  # BACKEND END
  #
  # ######################################################################

  # ======================================================================
  # Black Docs
  # ======================================================================
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==22.6.0]
  # ======================================================================
  # Black
  # ======================================================================
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [--config=pyproject.toml]
  # ======================================================================
  # Python Imports
  # ======================================================================
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: "\\.(py)$"
        args: [--settings-path=pyproject.toml]
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.0.4
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]
  # ######################################################################
  #
  # DEV OPS
  #
  # ######################################################################

  # ======================================================================
  #  YAML Linting
  # ======================================================================
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.27.1
    hooks:
      - id: yamllint
        args:
          [
            --format,
            colored,
            -d,
            '{extends: default, rules: {line-length: disable}}',
          ]
  # ======================================================================
  # Large Files, JSON, TOML, YAML, XML, Private Key, End of File
  # Trailing Whitespace, Pretty Format JSON
  # ======================================================================
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: check-xml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: pretty-format-json
        exclude: ''
      - id: trailing-whitespace
  # ======================================================================
  # Docker
  # ======================================================================
  - repo: https://github.com/hadolint/hadolint
    rev: v2.10.0
    hooks:
      - id: hadolint-docker
        args: [--ignore, DL3008, --ignore, DL3045, --ignore, DL3013, --failure-threshold, warning]
  # ======================================================================
  # Shell Scripts
  # ======================================================================
  - repo: https://github.com/bemeurer/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
        types: [file, shell]
